name: CI - Building and testing
on: [push]
jobs:
  build:
    name: CI - Building and testing
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Paris"
          timezoneMacos: "Europe/Paris"
          timezoneWindows: "Romance Standard Time"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots --no-transfer-progress verify
